language: node_js
node_js:
- '8'
addons:
  ssh_known_hosts:
  - t2.latata.pl
before_install:
- openssl aes-256-cbc -K $encrypted_5d2a9bb64424_key -iv $encrypted_5d2a9bb64424_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
script: yarn test && yarn build
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
